trigger:
- master

stages:
  - stage: build
    jobs:
    - job: BinaryGo
      strategy:
        matrix:
          linux:
            imageName: 'ubuntu-latest'
          mac:
            imageName: 'macOS-latest'
          windows:
            imageName: 'windows-latest'
      pool:
        vmImage: $(imageName)
      steps:
        - task: UseDotNet@2
          name: InstallDotNet6
          inputs:
            version: '6.x'
        - task: UseDotNet@2
          name: InstallDotNet5
          inputs:
            version: '5.x'

        - script: |
            dotnet new globaljson --force --sdk-version=6.0.101
            dotnet --version
            dotnet --list-sdks
          name: UseNet_6X
        - task: DotNetCoreCLI@2
          name: Restore_6X
          inputs:
            command: 'restore'
        - task: DotNetCoreCLI@2
          name: Build_6X
          inputs:
            command: 'build'
        - task: DotNetCoreCLI@2
          name: Test_6X
          inputs:
            command: 'test'
            arguments: '--logger "console;verbosity=detailed"'
        - script: |
            dotnet new globaljson --force --sdk-version=5.0.404
            dotnet --version
            dotnet --list-sdks
          name: UseNet_5X
        - task: DotNetCoreCLI@2
          name: Restore_5X
          inputs:
            command: 'restore'
        - task: DotNetCoreCLI@2
          name: Build_5X
          inputs:
            command: 'build'
        - task: DotNetCoreCLI@2
          name: Test_5X
          inputs:
            command: 'test'
            arguments: '--logger "console;verbosity=detailed"'