trigger:
- master

stages:
  - stage: build
    jobs:
    - job: BinaryGo
      strategy:
        matrix:
          linux:
            imageName: 'ubuntu-latest'
          mac:
            imageName: 'macOS-latest'
          windows:
            imageName: 'windows-latest'
      pool:
        vmImage: $(imageName)
      steps:
        - task: UseDotNet@2
          name: InstallDotNet6
          inputs:
            version: '6.x'
        - script: |
            dotnet new globaljson --force --sdk-version=6.x
            dotnet --version
          
        - task: DotNetCoreCLI@2
          name: Restore_6X
          inputs:
            command: 'restore'
        - task: DotNetCoreCLI@2
          name: Build_6X
          inputs:
            command: 'build'
        - task: DotNetCoreCLI@2
          name: Test_6X
          inputs:
            command: 'test'
            arguments: '--logger "console;verbosity=detailed"'
        - task: UseDotNet@2
          name: InstallDotNet5
          inputs:
            version: '5.x'
        - task: DotNetCoreCLI@2
          name: Use_5X
          inputs:
            command: 'custom'
            custom: 'new'
            arguments: 'globaljson --force --sdk-version=5.x'
          
        - task: DotNetCoreCLI@2
          name: Restore_5X
          inputs:
            command: 'restore'
        - task: DotNetCoreCLI@2
          name: Build_5X
          inputs:
            command: 'build'
        - task: DotNetCoreCLI@2
          name: Test_5X
          inputs:
            command: 'test'
            arguments: '--logger "console;verbosity=detailed"'
        - task: UseDotNet@2
          name: InstallDotNet3
          inputs:
            version: '3.x'
            packageType: runtime
        - task: DotNetCoreCLI@2
          name: Use_3X
          inputs:
            command: 'custom'
            custom: 'new'
            arguments: 'globaljson --force --sdk-version=3.x'
          
        - task: DotNetCoreCLI@2
          name: Restore_3X
          inputs:
            command: 'restore'
        - task: DotNetCoreCLI@2
          name: Build_3X
          inputs:
            command: 'build'
        - task: DotNetCoreCLI@2
          name: Test_3X
          inputs:
            command: 'test'
            arguments: '--logger "console;verbosity=detailed"'