trigger:
- master

stages:
  - stage: build
    jobs:
    - job: BinaryGo
      strategy:
        matrix:
          Windows:
            imageName: 'windows-latest'
          Linux:
            imageName: 'ubuntu-latest'
          Mac:
            imageName: 'macOS-latest'
      pool:
        vmImage: $(imageName)
      steps:
        - task: UseDotNet@2
          name: InstallDotNet3
          inputs:
            version: '3.x'
        - task: UseDotNet@2
          name: InstallDotNet2
          inputs:
            version: '2.x'
        - task: UseDotNet@2
          name: InstallDotNet6
          inputs:
            version: '6.x'
        - task: DotNetCoreCLI@2
          name: Build_6X
          inputs:
            command: 'build'
        - task: DotNetCoreCLI@2
          name: Test_6X
          inputs:
            command: 'test'
            arguments: '--logger -f net6.0 "console;verbosity=detailed"'
        - task: DotNetCoreCLI@2
          name: Test_5X
          inputs:
            command: 'test'
            arguments: '--logger -f net5.0 "console;verbosity=detailed"'
        - task: DotNetCoreCLI@2
          name: Test_3X
          inputs:
            command: 'test'
            arguments: '--logger -f netcoreapp3.1 "console;verbosity=detailed"'
        - task: DotNetCoreCLI@2
          name: Test_2X
          inputs:
            command: 'test'
            arguments: '--logger -f netcoreapp2.2 "console;verbosity=detailed"'
            
