trigger:
- master

stages:
  - stage: build
    jobs:
    - job: Build_Ubuntu
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            feedsToUse: 'select'
            vstsFeed: 'my-vsts-feed' # A series of numbers and letters

        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
              
        - task: UseDotNet@2
          inputs:
            version: '5.0.x'

        - task: UseDotNet@2
          inputs:
            version: '3.0.x'
            packageType: runtime

        - task: DotNetCoreCLI@2
          inputs:
            command: test

    - job: Build_Windows
      pool:
        vmImage: 'windows-latest'