trigger:
- master

stages:
  - stage: build
    jobs:
    - job: BinaryGo
      strategy:
        matrix:
          linux:
            imageName: 'ubuntu-latest'
          mac:
            imageName: 'macOS-latest'
          windows:
            imageName: 'windows-latest'
      pool:
        vmImage: $(imageName)
      steps:
        - task: UseDotNet@2
          name: InstallDotNet6
          inputs:
            version: '6.0.101'
        - task: DotNetCoreCLI@2
          name: Use_6X
          inputs:
            command: custom
            arguments: 'new globaljson --force --sdk-version=6.0.101'
          
        - task: DotNetCoreCLI@2
          name: Restore_6X
          inputs:
            command: 'restore'
        - task: DotNetCoreCLI@2
          name: Build_6X
          inputs:
            command: 'build'
        - task: DotNetCoreCLI@2
          name: Test_6X
          inputs:
            command: 'test'
            arguments: '--logger "console;verbosity=detailed"'
        - task: UseDotNet@2
          name: InstallDotNet5
          inputs:
            version: '5.0.403'
        - task: DotNetCoreCLI@2
          name: Use_5X
          inputs:
            command: custom
            arguments: 'new globaljson --force --sdk-version=5.0.403'
          
        - task: DotNetCoreCLI@2
          name: Restore_5X
          inputs:
            command: 'restore'
        - task: DotNetCoreCLI@2
          name: Build_5X
          inputs:
            command: 'build'
        - task: DotNetCoreCLI@2
          name: Test_5X
          inputs:
            command: 'test'
            arguments: '--logger "console;verbosity=detailed"'
        - task: UseDotNet@2
          name: InstallDotNet3
          inputs:
            version: '3.1.22'
            packageType: runtime
        - task: DotNetCoreCLI@2
          name: Use_3X
          inputs:
            command: custom
            arguments: 'new globaljson --force --sdk-version=3.1.22'
          
        - task: DotNetCoreCLI@2
          name: Restore_3X
          inputs:
            command: 'restore'
        - task: DotNetCoreCLI@2
          name: Build_3X
          inputs:
            command: 'build'
        - task: DotNetCoreCLI@2
          name: Test_3X
          inputs:
            command: 'test'
            arguments: '--logger "console;verbosity=detailed"'