trigger:
- master

stages:
  - stage: build
    jobs:
    - job: BinaryGo
      strategy:
        matrix:
          Windows:
            imageName: 'windows-latest'
          Linux:
            imageName: 'ubuntu-latest'
          Mac:
            imageName: 'macOS-latest'
      pool:
        vmImage: $(imageName)
      steps:
        - task: UseDotNet@2
          name: InstallDotNet3
          inputs:
            version: '3.x'
        - task: UseDotNet@2
          name: InstallDotNet2
          inputs:
            version: '2.x'
        - task: UseDotNet@2
          name: InstallDotNet5
          inputs:
            version: '5.x'
        - task: UseDotNet@2
          name: InstallDotNet6
          inputs:
            version: '6.x'
        - task: DotNetCoreCLI@2
          name: Build_6X
          inputs:
            command: 'build'
        - task: DotNetCoreCLI@2
          name: Test_6X
          inputs:
            command: 'test'
            arguments: '--logger "console;verbosity=detailed;" /Framework:Microsoft.NETCore.App;Version=v6.0.300'
        - task: DotNetCoreCLI@2
          name: Test_5X
          inputs:
            command: 'test'
            arguments: '--logger "console;verbosity=detailed"  /Framework:Microsoft.NETCore.App;Version=v5'
        - task: DotNetCoreCLI@2
          name: Test_3X
          inputs:
            command: 'test'
            arguments: '--logger "console;verbosity=detailed"'
            otherConsoleOptions: '/Framework:netcoreapp3.1'
        - task: DotNetCoreCLI@2
          name: Test_2X
          inputs:
            command: 'test'
            arguments: '--logger "console;verbosity=detailed"'
            otherConsoleOptions: '/Framework:netcoreapp2.2'
            
