trigger:
- master

stages:
  - stage: build
    jobs:
    - job: BinaryGo
      strategy:
        matrix:
          linux:
            imageName: 'ubuntu-latest'
          mac:
            imageName: 'macOS-latest'
          windows:
            imageName: 'windows-latest'
      pool:
        vmImage: $(imageName)
      steps:
        - task: UseDotNet@2
          name: InstallDotNet6
          inputs:
            version: '6.0.x'
        - task: UseDotNet@2
          name: InstallDotNet5
          inputs:
            version: '5.0.x'

        - task: UseDotNet@2
          name: InstallDotNet3
          inputs:
            version: '3.0.x'
            packageType: runtime

        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            feedsToUse: 'select'
            vstsFeed: 'my-vsts-feed' # A series of numbers and letters
              
        - task: DotNetCoreCLI@2
          name: Build
          inputs:
            command: 'build'
        - task: VSTest@2
          name: Test
          inputs:
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'
              codeCoverageEnabled: true
              runInParallel: true